var mongoose = require("mongoose")
//SCHEMA SETUP
var washingMachineSchema = new mongoose.Schema({
    barcodeId: Number,
    productModelCoreId: Number,
    productGroup: String,
    versionId: Number,
    modelIdentifier: String,
    energyClass: String,
    energyClassImage: String,
    energyLabelId: Number,
    supplierOrTrademark: String,
    contactId: Number,
    onMarketEndDate: Date,
    onMarketEndDateTS: Date,
    versionNumber: String,
    registrantNature: String,
    implementingAct: String,
    lastVersion: Boolean,
    trademarkId: String,
    skipScaleValidation: Boolean,
    ratedCapacity: String,
    dimensionHeight: String,
    dimensionWidth: String,
    dimensionDepth: String,
    energyEfficiencyIndex: String,
    washingEfficiencyIndex: String,
    rinsingEffectiveness: String,
    energyCons: String,
    energyConsPerCycle: String,
    waterCons: String,
    maxTemperatureRated: String,
    maxTemperatureHalf: String,
    maxTemperatureQuarter: String,
    moistureRated: String,
    moistureHalf: String,
    moistureQuarter: String,
    spinSpeedRated: String,
    spinSpeedHalf: String,
    spinSpeedQuarter: String,
    spinClass: String,
    programmeDurationRated: String,
    programmeDurationHalf: String,
    programmeDurationQuarter: String,
    type: String,
    noise: String,
    noiseClass: String,
    powerOffMode: String,
    powerStandbyMode: String,
    powerDelayStart: String,
    powerNetworkStandby: String,
    guaranteeDuration: Number,
    releasesSilverIons: Boolean,
    webLinkSupplier: String,
})

//Compile into model
module.exports = mongoose.model("WashingMachine", washingMachineSchema)
